name: kirstu
channels:
  - default
  - conda-forge
  - bioconda
dependencies:
  - python==3.7  
  - numpy
  - scipy
  - scikit-image
  - ipython
  - jupyter
  - notebook
  - matplotlib
  - h5py
  - pillow
  - pip
  - pip:
    - nibabel
    - gendocs
    - cookiecutter
    - sphinx_rtd_theme
